config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'home' => 'pages#home'
  root 'pages#home'

  resources :skills, only: [ :index, :new, :create, :update, :edit, :show] do
    resources :projects, only: [:new, :create, :show]
  end

  resources :users

  namespace :account do
    resources :skills
    resources :projects, except: [ :destroy]
  end
’

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :skill
  belongs_to :user

  validates :status, presence: true
  validates :check_out, presence: true
  validates :price, presence: true
  validates :number_of_hours, presence: true

end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :project

  validates :description, presence: true
  validates :description, length: { minimum: 10 }
  validates :skill_rating, inclusion: { in: [1,2,3,4,5], allow_nil: false }
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  belongs_to :user
  has_many :projects

  validates :name, presence: true
  validates :description, presence: true
  validates :level, presence: true
  validates :price_per_hour, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :skills
  has_many :reviews
  has_many :projects

  # validates :first_name, presence: true
  # validates :last_name, presence: true
  # validates :email, format: { with: /[a-zA-Z0-9._-]+@[a-z0-9._-]{2,}\.[a-z]{2,4}/ }, uniqueness: true
  # validates :address, presence: true
  # validates :description, length: { minimum: 10 }

end

app/controllers/account/projects_controller.rb
module Account
  class ProjectsController < ApplicationController
    before_action :find_project, only: [:show, :edit]

    def index
      @projects = current_user.projects
    end

    def new
      @project = Project.new
    end

    def show
    end


    def edit
    end

    def update
      @project = Project.find(project_params)
      @project.update(params[:project])
      redirect_to account_projects_path(@project)
    end

    private

    def find_project
      @project = Project.find(params[:id])
    end

    def project_params
      params.require(:project).permit(:name, :status, :price, :number_of_hours, :check_out)
    end
  end

end

app/controllers/account/skills_controller.rb
module Account
  class SkillsController < ApplicationController
    # before_action :set_user , only: [:create]

    def index
      @skills = current_user.skills
    end

    def new
      @skill = Skill.new
    end

    def create
      @skill = Skill.new(skill_params)
      @skill.user = current_user
      if @skill.save
        redirect_to account_skills_path
      else
        render :new
      end
    end

    def edit
    end

    def show
    end

    def update
    end


    private

    # def set_user
    #   @user =User.find(params[:user_id])
    # end

    def skill_params
      params.require(:skill).permit(:name, :description, :level, :price_per_hour)
    end

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :authenticate_user!
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end





end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :find_project, only: [:show, :edit]

  def new
    @project = Project.new
    @skill = Skill.find(params[:skill_id]) # form for dit qu'il faut egalement trouver et donner id de skill
  end

  def create
    @project.user = current_user # je veux le user du project, Pour l'imprication commencer par le haut
    @project.skill = Skill.find(params[:skill_id]) # je veux la kill du project, imprication liee au nestage
    @project = Project.new(project_params) #veut le contenus du formulaire
    if @project.save  #je sauvegarde
      redirect_to account_projects_path(@project)  # Je redirige
    else
      render :new
    end
  end

  def show
  end


  def edit
  end

  def update
    @project.update(params[:project])
    @project = Project.find(project_params)
    redirect_to account_projects_path
  end

  private

  def find_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:name, :status, :price, :number_of_hours, :check_out)
  end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  # before_action :set_user , only: [:create]

  def index
    @skills = Skill.where(name: params[:search_term]) # index avec comme filtre la recherche utilisateur
  end

  def new
      @skill = Skill.new
  end

  def edit
  end

  def create
    @skill = Skill.new(skill_params)
    @skill.user = current_user
    if @skill.save
      redirect_to skill_path(@skill)
    else
      render :new
    end
  end

  def show
  end

  def update
  end


  private

  # def set_user
  #   @user =User.find(params[:user_id])
  # end

  def skill_params
    params.require(:skill).permit(:name, :description, :level, :price_per_hour)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def index
    @users=User.all

  end

  def show
    @skill = Skill.new
    @skills = current_user.skills

  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.save ? (redirect_to home_path) : (render :new)
  end

  def edit
    @user = current_user
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path
  end

  def destroy
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :gender, :phone_number, :description, :address, :email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Adopteundev</title>

  <%= stylesheet_link_tag    'application', media: 'all' %>

  <%= csrf_meta_tags %>
</head>
<body>


<%= render 'shared/navbar'%>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>
<%= javascript_include_tag 'application' %>
<%= yield :after_js %>


</body>
</html>

app/views/pages/home.html.erb
<div class="banner text-center">
 <div class="banner-shadow"></div>
 <div class="banner-content">
   <h1>Turn Big Ideas into Great Products</h1>

   <div>
     <h3> Millions of startup use our platform to turn their ideas into reality. <br>Need to get work done?</br> Search an expert to get started!</h3>
   </div>

 </div>


<!--Searchbar-->
 <div class="searchbar">
  <form action="/skills" class='form-inline' method="get">
      <input type="text" name="search_term" class="searchbar-input form-control">
      <button type="submit" class="btn btn-primary">Rechercher</button>
  </form>
   <div>
    <h4>Are you talented and looking for work? <%= link_to "Sign up as ninja", new_user_registration_path%></h4>
  </div>
 </div>
</div>


<div class="bg-grey">
  <div class="container">
    <div class="row text-center">
      <div class="col-xs-12 col-sm-6 col-md-3"><h4>Create your project</h4>
        <div><p>Describe what you need to do and tell us your budget.</p></div>
      </div>
      <div class="col-xs-12 col-sm-6 col-md-3"><h4>Add your skills</h4>
        <div><p>Start earn money from fancy projects all around the world.</p></div>
      </div>
      <div class="col-xs-12 col-sm-6 col-md-3", "card-home"><h4>Choose your coding ninja</h4>
        <div><p>Receive competitive quotes and choose the right freelance.</p></div>
      </div>
      <div class="col-xs-12 col-sm-6 col-md-3"><h4>Work done !</h4>
        <div><p>The freelance complete the work. You only pay when you are satisfied.</p></div>
      </div>
    </div>
  </div>
</div>

<div class="bg-black text-center">
  <h1 class="padded-top-small">GET INSPIRED FROM FANCY PROJECTS</h1>
  <p class="padded-bottom-small">You can get anything done on Adopt a dev. Which great idea will you launch today?</p>
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-9">
        <div class="card-home card-home-panoramic text-center">
          <img src="https://cdn5.f-cdn.com/build/css/abtests/20150608/images/showcase/large/web-design-development.jpg?v=87e605e2400c597b2a1f7c7629440df8&m=5" alt="">
          <div class="card-content">
            <h4>Webdesign and Dévelopment</h4>
            <p>Starting from 100€</p>
          </div>

        </div>

      </div>
      <div class="col-xs-12 col-sm-3">
        <div class="card-home card-home-square text-center">
          <img src="https://cdn2.f-cdn.com/build/css/abtests/20150608/images/showcase/large/software-development.jpg?v=dcbb56d7082d0d80641cd8325aaec229&m=5" alt="">
          <div class="card-content">
            <h4>Software Development</h4>
            <p>Starting from 175€</p>
          </div>

        </div>

      </div>
      <div class="col-xs-12 col-sm-9">
        <div class="card-home card-home-panoramic text-center">
          <img src="https://cdn6.f-cdn.com/build/css/abtests/20150608/images/showcase/large/mobile-app-design-and-development.jpg?v=0b12c23c7e2bb8ebb89fe5d95598e1b9&m=5" alt="">
          <div class="card-content">
            <h4>Mobile App Development</h4>
            <p>Starting from 250€</p>
          </div>
        </div>

      </div>
      <div class="col-xs-12 col-sm-3">
        <div class="card-home card-home-square text-center">
          <img src="https://cdn3.f-cdn.com/build/css/abtests/20150608/images/showcase/large/seo-and-marketing.jpg?v=81466a409fe6da5ae19d2a274b48dcf6&m=5" alt="">
          <div class="card-content">
            <h4>SEO & Marketing</h4>
            <p>Starting from 15€</p>
          </div>

        </div>

      </div>
    </div>
  </div>
</div>

app/views/project/show.html.erb
<h1>show project</h1>

<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= @project.name %>
      <%= @project.status %>
      <%= @project.check_out %>
      <%= @project.price %>
      <%= @project.number_of_hours %>
      <%= @project.skill_id %>
      <%= @project.user_id %>
    </div>
  </div>
</div>

app/views/projects/index.html.erb
<ul>
  <% @project.each do |project| %>
    <li><%= project.name, project_path(project) %></li>
  <% end %>
</ul>

app/views/projects/new.html.erb
<h1 class="text-center">Booking a skill</h1>


<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= simple_form_for [@skill, @project] do |f| %>
        <%= f.error_notification %>
        <%= f.input :name, placeholder: "name" %>
        <%= f.label :check_out, class: 'control-label' %>
        <%= f.text_field :check_out, class: 'form-control datepicker' %>
        <%= f.input :status, collection: ["En cours", "Validé"], prompt: "Status", selected: 2 %>
        <%= f.input :price, placeholder: "price"%>
        <%= f.input :number_of_hours, placeholder: "number of hours"%>
        <%= f.button :submit %>
      <% end %>
    </div>
  </div>
  <% content_for :after_js do %>
  <% end %>
</div>

app/views/projects/show.html.erb
<h1>show project</h1>

<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= @project.name %>
      <%= @project.status %>
      <%= @project.check_out %>
      <%= @project.price %>
      <%= @project.number_of_hours %>
      <%= @project.skill_id %>
      <%= @project.user_id %>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar-wagon">
  <div class="container navbar-wagon-container">

    <a href="/">
      <%= image_tag "train-logo.png",width: "160px" %>
    </a>

    <form action="" class="navbar-wagon-search">
<!--       <input type="text" class="navbar-wagon-search-input" placeholder="Search for featured stuff">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button> -->
    </form>
    <hr>
    <% if user_signed_in? %>
<!--       <%= link_to "#", class: "navbar-wagon-item navbar-wagon-link hidden-xs" do %>
        <div class="icon-badge-container">
          <i class="fa fa-envelope-o"></i>
          <div class="icon-badge icon-badge-blue">3</div>
        </div>
      <% end %>
      <hr> -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <span class="padded"><%= current_user.first_name %></span>
          <%= image_tag current_user.avatar, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "/" do %>
                <i class="fa fa-home"></i>  <%= t ".profile", default: "Home" %>
              <% end %>
            </li>
            <li>
              <%= link_to "/users/:id(.:format) " do %>
                <i class="fa fa-user"></i> <%= t ".profile", default: "Profile" %>
              <% end %>
            </li>
            <li>
              <%= link_to account_skills_path do %>
                <i class="fa fa-graduation-cap"></i>  <%= t ".profile", default: "Skills" %>
              <% end %>
            </li>
            <li>
              <%= link_to account_projects_path do %>
                <i class="fa fa-file-text"></i>  <%= t ".profile", default: "Projects" %>
              <% end %>
            </li>
            <li>
              <%= link_to edit_user_registration_path do %>
                <i class="fa fa-cog"></i>  <%= t ".profile", default: "Settings" %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t ".sign_out", default: "Log out" %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
      <hr>
      <%= link_to t(".top_call_to_action", default: "Add your skill"), new_account_skill_path, class: "navbar-wagon-item navbar-wagon-button btn" %>
    <% else %>
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
    <hr>
  </div>
</nav>

app/views/skills/create.html.erb
<h1>Skills#create</h1>
<p>Find me in app/views/skills/create.html.erb</p>

app/views/skills/edit.html.erb
<h1>Skills#edit</h1>
<p>Find me in app/views/skills/edit.html.erb</p>

app/views/skills/index.html.erb
<h1 class="text-center">List of skills</h1>


<div class="container">
  <div class="row">
    <% @skills.each do |skill| %>
      <div class="col-xs-12 col-sm-4">
        <div class="card">
          <span class="card-bg" style="background-image: url('http://www.dvi43.com/wp-content/uploads/2015/01/geek.jpg')">
          </span>
          <span class="card-shadow"></span>
          <span class="card-description"><%= skill.level %></span>
          <span class="card-text">
            <h2><%= skill.name %></h2>
            <p><%= skill.description %></p>
            <p class="btn btn-danger"><%= "Adopte moi !!!" %></p>
          </span>
          <span class="card-user">
            <%= image_tag skill.user.avatar, class:"avatar avatar-bordered" %>
          </span>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/skills/new.html.erb
<div class= "text-center">
<h1>Add your ninja skills</h1>
<h3>Today is the day you start earn money </h3>
</div>




<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
       <%= simple_form_for @skill do |f| %>
       <%=f.input :name, collection: ["Ruby", "HTML", "PHP"], selected: ["Ruby"] %>
       <%=f.input :description, placeholder: "write a little story here about your experience" %>
       <%=f.input :level, collection: ["Newbie", "Padawan", "Master", "Ninja"], selected: ["Newbie"] %>
       <%=f.input :price_per_hour, placeholder: "your price four a hour" %>
       <%=f.button :submit, class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
  <%= link_to "back", users_path%>
</div>

app/views/skills/show.html.erb
<h1>Skills#show</h1>
<p>Find me in app/views/skills/show.html.erb</p>



  <div class="card">
    <span class="card-bg"></span>
      <span class="card-shadow"></span>
        <span class="card-description">Popular</span>
          <span class="card-text">
            <h2><%= @skill.name %></h2>
            <p>Very cool stuff, useful and smart</p>
          </span>
        <span class="card-user">
          <img src='user.jpg' class="avatar avatar-bordered"/>
        </span>
    <a href="#" class="card-link"></a>
  </div>

app/views/skills/update.html.erb
<h1>Skills#update</h1>
<p>Find me in app/views/skills/update.html.erb</p>

app/views/users/_card.html.erb
<!-- <div class="card">
  <span class="card-bg"></span>
  <span class="card-shadow"></span>
  <span class="card-description">Popular</span>
  <span class="card-text">
    <h2>Some stuff</h2>
    <p>Very cool stuff, useful and smart</p>
  </span>
  <span class="card-user">
    <img src='user.jpg' class="avatar avatar-bordered"/>
  </span>
  <a href="https://unsplash.it/200/200?" class="card-link"></a>
</div> -->


<div class="card">
 <span class="card-bg" style="background-image: url('https://unsplash.it/200/200?')">

 </span>
 <span class="card-shadow"></span>
 <span class="card-description">Popular</span>
 <span class="card-text">
   <h2><%= user.first_name %></h2>
   <p><%= "Smooth & strong" %>
 </span>
<!--   <span class="card-user">
   <img src='user.jpg' class="avatar avatar-bordered"/>
 </span> -->
</div>

app/views/users/edit.html.erb
<div class= "text-center">
  <h1>Update your profile</h1>
  <h3>Complete your profile</h3>
</div>

<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <%= simple_form_for (@user) do |f| %>
      <%=f.input :first_name, placeholder: "John"%>
      <%=f.input :last_name, placeholder: "Doe" %>
      <%= f.input :gender, as: :radio_buttons,
          collection: ['Male', 'Female'], wrapper: :vertical_radio_and_checkboxes %>
      <%=f.input :phone_number, placeholder: "+33 XXX XX XX XX" %>
      <%=f.input :description, placeholder: "Description" %>
      <%=f.input :address, placeholder: "16 villa gaudelet, 75011 Paris" %>
      <%=f.input :email, placeholder: "john.doe@gmail.com" %>

      <%=f.button :submit, class: "btn btn-primary" %>
      <%= link_to "back", users_path%>
     <% end %>
    </div>
  </div>
<%= link_to "Change your password", edit_user_registration_path %>
</div>

app/views/users/show.html.erb
<h1 class="text-center">Your Profile</h1>

<div class="text-center">
  <h1>Your personal info</h1>
  <p><%= current_user.first_name %></p>
  <p><%= current_user.email %></p>
</div>


<div class="container">
  <div class="row">
    <% @skills.each do |skill| %>
      <div class="col-xs-12 col-sm-4">
        <div class="card">
          <span class="card-bg" style="background-image: url('http://www.dvi43.com/wp-content/uploads/2015/01/geek.jpg')">
          </span>

          <span class="card-shadow"></span>
          <span class="card-description"><%= skill.level %></span>
          <span class="card-text">
            <h2><%= skill.name %></h2>
            <p><%= skill.description%></p>
          </span>
          <span class="card-user">
            <%= image_tag current_user.avatar, class:"avatar avatar-bordered" %>
          </span>
        </div>
      </div>
    <% end %>
  </div>
</div>